# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from 'C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\numpy\\version.py'>
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Admin/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include

#### 3. Create a null vector of size 10

In [6]:
arr=np.zeros(10)
print (arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [7]:
arr= np.zeros((5,4))
print("%d bytes" %(arr.size*arr.itemsize))

160 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [39]:
python -c "import numpy; numpy,info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-39-657ca85a8898>, line 1)

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [8]:
arr= np.zeros(10)
print(arr)
arr[4]=1
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [12]:
arr=np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last)

In [13]:
arr= arr[::-1]
print(arr)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [25]:
arr=np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [15]:
arr=np.identity(3)
print (arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [17]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.89413649 0.46899261 0.73754048]
  [0.23957636 0.72813476 0.19393325]
  [0.25310025 0.94837218 0.6828618 ]]

 [[0.52569165 0.67254543 0.91263847]
  [0.00965644 0.57795569 0.16728065]
  [0.18840398 0.9752406  0.74247578]]

 [[0.82081526 0.55867253 0.54088238]
  [0.30135828 0.2204044  0.39726184]
  [0.67106018 0.2610552  0.44290138]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [19]:
arr= np.random.random((10,10))
print(arr)
amax=arr.max()
print("Maximun")
print(amax)
amin=arr.min()
print("Minimum")
print(amin)

[[0.18818416 0.71069365 0.36449888 0.66221737 0.02340557 0.07796366
  0.15049783 0.53850562 0.52191403 0.59959721]
 [0.28250359 0.86251586 0.411776   0.69525126 0.19844672 0.39385538
  0.48328905 0.88705429 0.53545499 0.6892648 ]
 [0.4498567  0.62968308 0.67513191 0.61324587 0.52056392 0.39180711
  0.42050461 0.71386475 0.77451431 0.34824437]
 [0.84452363 0.89905024 0.64271474 0.88341593 0.83549577 0.13700621
  0.62666994 0.18142914 0.98092063 0.09081024]
 [0.85246972 0.34343631 0.66544529 0.02686114 0.4629212  0.67508073
  0.58560045 0.7905911  0.43051601 0.46259152]
 [0.92472049 0.8345014  0.69093278 0.35184317 0.35751072 0.13449665
  0.45552112 0.52500934 0.27829844 0.17251248]
 [0.38006832 0.82646393 0.22319856 0.6929804  0.60168798 0.64417796
  0.7707782  0.17587745 0.84425215 0.1929882 ]
 [0.78394238 0.18890113 0.2311588  0.99479427 0.64275541 0.66719668
  0.84549233 0.24865411 0.36483015 0.37754152]
 [0.61745315 0.24744695 0.58739133 0.85240635 0.90416023 0.99703645
  0.54937939

#### 14. Create a random vector of size 30 and find the mean value

In [21]:
arr=np.random.random((30))
print(arr)
amean=arr.mean()
print("Mean")
print(amean)

[0.59510092 0.06080904 0.47961593 0.47228048 0.72883773 0.96764306
 0.88506324 0.20424375 0.47958751 0.63163326 0.57345105 0.27099319
 0.84970241 0.44251141 0.4052707  0.7111389  0.29208558 0.94146104
 0.93130284 0.46543386 0.44539537 0.18423415 0.41594446 0.58527173
 0.31624365 0.39483566 0.86977607 0.32127553 0.8287683  0.05169651]
Mean
0.5267202432114078


#### 15. Create a 2d array with 1 on the border and 0 inside

In [27]:
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [29]:
arr=np.ones((4,4))
print(arr)
arr=np.pad(arr, pad_width=1,mode='constant',constant_values=0)
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [37]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [30]:
arr=np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [34]:
arr=np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [35]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
